# Generated by Django 4.0.6 on 2022-08-04 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodie', '0003_alter_address_user_id_alter_paymentmethod_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businessextra',
            name='user_extra_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodie.userextra'),
        ),
        migrations.AlterField(
            model_name='businessextra',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodie.businessextra'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodie.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodie.menu'),
        ),
        migrations.AlterField(
            model_name='default',
            name='address_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='foodie.address'),
        ),
        migrations.AlterField(
            model_name='default',
            name='payment_method_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='foodie.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='default',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliverypersonextra',
            name='user_extra_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodie.userextra'),
        ),
        migrations.AlterField(
            model_name='deliverypersonextra',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodie.businessextra'),
        ),
        migrations.AlterField(
            model_name='order',
            name='offer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodie.offer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodie.businessextra'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodie.menu'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodie.order'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
