# Generated by Django 4.0.6 on 2022-08-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0005_contact_alter_default_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
