# Generated by Django 4.0.6 on 2022-08-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0006_order_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
