# Generated by Django 4.0.6 on 2022-08-05 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0005_alter_default_user_id'),
        ('foodie', '0007_orderitem_quantity'),
    ]

    operations = [
    ]
