# Generated by Django 4.0.6 on 2022-08-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0008_cartitem_quantity_order_delivery_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='cardtype',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Master Card'), ('americanexpress', 'American Express'), ('discover', 'Discover')], max_length=50, null=True),
        ),
    ]
