# Generated by Django 4.0.6 on 2022-08-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0009_userprofile_alter_order_offer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
