# Generated by Django 4.0.6 on 2022-08-05 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0009_alter_paymentmethod_cardtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='address_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='foodie.address'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment_method_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='foodie.paymentmethod'),
        ),
    ]
