# Generated by Django 4.0.6 on 2022-08-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0008_merge_20220804_2027'),
        ('foodie', '0011_remove_orderitem_address_id_and_more'),
    ]

    operations = [
    ]
