# Generated by Django 4.1 on 2022-08-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0011_remove_orderitem_address_id_and_more'),
        ('foodie', '0012_userprofile_user_id'),
    ]

    operations = [
    ]
