# Generated by Django 4.0.6 on 2022-08-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0013_favoriterestaurant_favoriteitem'),
        ('foodie', '0013_merge_20220805_0714'),
    ]

    operations = [
    ]
