# Generated by Django 4.0.6 on 2022-08-05 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodie', '0014_merge_20220805_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingReviewRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('review', models.TextField(null=True)),
                ('restaurant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='foodie.businessextra')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restaurant_rating_review',
            },
        ),
    ]
