# Generated by Django 4.1 on 2022-08-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0015_ratingreviewrestaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.TextField(null=True),
        ),
    ]
