# Generated by Django 4.1 on 2022-08-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0016_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLoaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_loaded', models.BooleanField(null=True)),
            ],
        ),
    ]
