from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = "foodie"

urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about_us, name="about_us"),
    path("contact", views.contact_us, name="contact_us"),
    path("login", views.login_view, name="login"),
    path("signup", views.signup, name="signup"),
    path("help", login_required(views.help, login_url='/login'), name="help"),
    path('cart', login_required(views.cart_view,
         login_url='/login'), name="cart_view"),
    path("logout", login_required(views.logout_view,
         login_url='/login'), name="logout"),
    path("user-profile", login_required(views.userprofiles,
         login_url='/login'), name="userprofile"),
    path("search-restaurants", login_required(views.search_restaurants,
         login_url='/login'), name="search_restaurants"),
    path("edit-menu-item/<int:menu_id>", login_required(views.edit_menu_item,
         login_url='/login'), name="edit_menu_item"),
    path("add-menu-item", login_required(views.add_menu_item,
         login_url='/login'), name="add_menu_item"),
    path("set-default-address", login_required(views.add_default_address,
         login_url='/login'), name="add_default_address"),
    path("addresses", login_required(views.addresses,
         login_url='/login'), name="addresses"),
    path("payment-methods", login_required(views.payment_methods,
         login_url='/login'), name="payment_methods"),
    path("restaurant/<int:restaurant_id>", login_required(views.restaurant_view,
         login_url='/login'), name="restaurant_view"),
    path("add-cart-item/<int:item_id>", login_required(views.add_cart_items,
         login_url='/login'), name="add_cart_items"),
    path("update-cart/<str:action>", login_required(views.cart_item_quanity_update,
         login_url='/login'), name="cart_item_quanity_update"),
    path("add-address", login_required(views.add_address,
         login_url='/login'), name="add_address"),
    path("add-payment-method", login_required(views.add_payment_method,
         login_url='/login'), name="add_payment_method"),
    path("edit-payment-method/<int:payment_method_id>", login_required(views.edit_payment_method,
         login_url='/login'), name="edit_payment_method"),
    path("edit-address/<int:address_id>", login_required(views.edit_address,
         login_url='/login'), name="edit_address"),
    path("checkout", login_required(
        views.checkout, login_url='/login'), name="checkout"),
    path("business-orders", login_required(views.business_orders,
         login_url='/login'), name="business_orders"),
    path("delivery-person-orders", login_required(views.delivery_person_orders,
         login_url='/login'), name="delivery_person_orders"),
    path("orderhistory", login_required(views.order_history,
         login_url='/login'), name="order_history"),
    path("user", login_required(views.user_view,
         login_url='/login'), name="user_view"),
    path("order-details/<int:order_id>", login_required(views.order_details,
         login_url='/login'), name="order_details"),
    path("add-favorite-restaurant/<int:restaurant_id>", login_required(views.add_favorite_restaurant,
         login_url='/login'), name="add_favorite_restaurant"),
    path("add-favorite-item/<int:item_id>", login_required(views.add_favorite_item,
         login_url='/login'), name="add_favorite_item"),
    path("order-confirm/<int:order_id>", login_required(views.confirm_order,
         login_url='/login'), name="confirm_order"),
    path("order-prepare/<int:order_id>", login_required(views.prepare_order,
         login_url='/login'), name="prepare_order"),
    path("order-ready/<int:order_id>", login_required(views.ready_order,
         login_url='/login'), name="ready_order"),
    path("order-delivery-accept/<int:order_id>", login_required(views.accept_order_delivery,
         login_url='/login'), name="accept_order_delivery"),
    path("order-out-delivery/<int:order_id>", login_required(views.order_out_delivery,
         login_url='/login'), name="order_out_delivery"),
    path("order-delivered/<int:order_id>", login_required(views.order_delivered,
         login_url='/login'), name="order_delivered"),
    path("menu-items", login_required(views.menu_items,
         login_url='/login'), name="menu_items"),
    path("review-restaurant/<int:restaurant_id>", login_required(views.restaurant_review,
         login_url='/login'), name="restaurant_review"),
    path("favorites", login_required(views.favorites,
         login_url='/login'), name="favorites"),
    path("signup-extra", views.extra_information, name="extra_information"),
]
